{"functionName":"test","params":{},"level":"info","message":"Ran cloud function test for user undefined with:\n  Input: {}\n  Result: \"Hello World!\"","timestamp":"2018-04-20T05:06:55.723Z"}
{"functionName":"test","params":{},"level":"info","message":"Ran cloud function test for user undefined with:\n  Input: {}\n  Result: \"Hello World!\"","timestamp":"2018-04-20T05:07:57.827Z"}
{"functionName":"test","params":{},"level":"info","message":"Ran cloud function test for user undefined with:\n  Input: {}\n  Result: \"Hello World!\"","timestamp":"2018-04-20T05:17:31.679Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-20T05:17:33.646Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-20T05:17:33.649Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-20T05:17:33.649Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-20T05:51:57.945Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-20T05:51:57.951Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-20T05:51:57.954Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-04-20T05:51:57.956Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-04-20T05:51:57.959Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-20T05:52:18.101Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-20T05:52:18.111Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-20T05:52:18.114Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-04-20T05:52:18.117Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-04-20T05:52:18.120Z"}
